### ISSUE TITLE
Signal has a "fizz"

### ISSUE THREAD

**Issue by cyrusadkisson** [brummer10/XTinyTerror.lv2#2]
Unfortunately, there is a deal-breaking "shhhh" fizz that you get regardless of the gain level when using this plugin.

**Comment by brummer10** [comment]
do you using a arm device?

**Comment by cyrusadkisson** [comment]
Withdrawing this issue. I hear a very slight fizz when plucking/strumming (not nearly as prominent as Dark Terror) but my Line 6 Helix "Mandarin" (orange) patch has this same slight fizz as well. Maybe it's just the way it is.

I'll talk to you over on the dark terror issue.
