### ISSUE TITLE
Doesn't work at 96Khz 

### ISSUE THREAD

**Issue by Gimmeapill** [brummer10/XTinyTerror.lv2#3]
Hi Hermann,

XTinyTerror doesn't seem to work here at 96Khz (Arch Linux).
It just produces a few noises and goes silent.
I tested in the folllwing hosts: Mixbus,Ardour, & Renoise through Carla.
DarkTerror has no problem (and sounds very nice).

**Comment by brummer10** [comment]
Hi
Okay, I've pushed a Fix for it to the repository. 
Glade you like the DarkTerror.

**Comment by Gimmeapill** [comment]
Thanks, I can confirm that the issue is fixed.

**Comment by brummer10** [comment]
Okay, then I'll close this issue. 
regards
hermann
